***(
 Analysis with I-S
***)

load ex-vaccines2 .

mod TEST is
    pr VACCINES .

    --- --------------------
    var STATE      : State .
    var SETEDGE SE : SetEdge .
    var AG         : Agent .
    --- --------------------

    --- eq model = i-s .
    eq moduleName = 'TEST .
    eq update(STATE, SETEDGE, AG) = update-i-s(STATE, SETEDGE, AG) .
    eq strategy(SE, STATE) = i-s(SE, STATE) .
endm

--- search  init =>* STATE such that consensus(STATE) .