***(
 Analysis with I-S
***)

load grafo-X .

mod TEST is
    pr VACCINES .

    --- --------------------
    var STATE : State .
    var SE    : SetEdge .
    var AG    : Agent .
    --- --------------------

    eq moduleName = 'TEST .
    eq update(STATE, SE, AG) = update-x-s(STATE, SE, AG) .
    eq strategy(SE, STATE) = i-x(SE, STATE) .
endm

eof

search  init =>* STATE such that consensus(STATE) .