***(
 Analysis with I-E
***)

load grafo-I .

mod TEST is
    pr VACCINES .

    --- --------------------
    var STATE : State .
    var SE    : SetEdge .
    var AG    : Agent .
    --- --------------------

    eq moduleName = 'TEST .
    eq update(STATE, SE, AG) = update-i-e(STATE, SE, AG) .
    eq strategy(SE, STATE) = i-e(SE, comm(STATE) + steps(STATE)) .
endm

eof

search  init =>* STATE such that consensus(STATE) .s